# Title: Heart Disease Prediction: A Comprehensive Approach

`Author:` [Sufwan Mubeen](https://www.kaggle.com/sufwanmubeen)\
`Date:` October 03, 2024\
`DataSet:` [Heart Disease Data](https://www.kaggle.com/datasets/redwankarimsony/heart-disease-data/data)


![](https://miro.medium.com/v2/resize:fit:1400/0*P-EN5Z4l3LbWg4V8)

## Meta-Data (About Dataset)
### Context
This is a multivariate type of dataset which means providing or involving a variety of separate mathematical or statistical variables, multivariate numerical data analysis. It is composed of 14 attributes which are age, sex, chest pain type, resting blood pressure, serum cholesterol, fasting blood sugar, resting electrocardiographic results, maximum heart rate achieved, exercise-induced angina, oldpeak â€” ST depression induced by exercise relative to rest, the slope of the peak exercise ST segment, number of major vessels and Thalassemia. This database includes 76 attributes, but all published studies relate to the use of a subset of 14 of them. The Cleveland database is the only one used by ML researchers to date. One of the major tasks on this dataset is to predict based on the given attributes of a patient that whether that particular person has heart disease or not and other is the experimental task to diagnose and find out various insights from this dataset which could help in understanding the problem more.

### Content
#### Column Descriptions:
1. `id` (Unique id for each patient)
2. `age` (Age of the patient in years)
3. `origin` (place of study)
4. `sex` (Male/Female)
5. `cp` chest pain type 
   1. typical angina
   2. atypical angina
   3. non-anginal
   4. asymptomatic
6. `trestbps` resting blood pressure (resting blood pressure (in mm Hg on admission to the hospital))
7. `chol` (serum cholesterol in mg/dl)
8. `fbs` (if fasting blood sugar > 120 mg/dl)
9.  `restecg` (resting electrocardiographic results)
-- Values: [normal, stt abnormality, lv hypertrophy]
1.  `thalch:` maximum heart rate achieved
2.  `exang:` exercise-induced angina (True/ False)
3.  `oldpeak:` ST depression induced by exercise relative to rest
4.  `slope:` the slope of the peak exercise ST segment
5.  `ca:` number of major vessels (0-3) colored by fluoroscopy
6.  `thal:` [normal; fixed defect; reversible defect]
7.  `num:` the predicted attribute
### Acknowledgements
#### Creators:
* Hungarian Institute of Cardiology. Budapest: Andras Janosi, M.D.
* University Hospital, Zurich, Switzerland: William Steinbrunn, M.D.
* University Hospital, Basel, Switzerland: Matthias Pfisterer, M.D.
* V.A. Medical Center, Long Beach and Cleveland Clinic Foundation: Robert Detrano, M.D., Ph.D.
#### Relevant Papers:
* Detrano, R., Janosi, A., Steinbrunn, W., Pfisterer, M., Schmid, J., Sandhu, S., Guppy, K., Lee, S., & Froelicher, V. (1989). International application of a new probability algorithm for the diagnosis of coronary artery disease. American Journal of Cardiology, 64,304--310.[Web Link](http://rexa.info/paper/b884ce2f4aff7ed95ce7bfa7adabaef46b88c60c)
* David W. Aha & Dennis Kibler. "Instance-based prediction of heart-disease presence with the Cleveland database." [Web Link](http://rexa.info/paper/0519d1408b992b21964af4bfe97675987c0caefc)
* Gennari, J.H., Langley, P, & Fisher, D. (1989). Models of incremental concept formation. Artificial Intelligence, 40, 11--61. [Web Link](http://rexa.info/paper/faecfadbd4a49f6705e0d3904d6770171b05041f)
#### Citation Request:
The authors of the databases have requested that any publications resulting from the use of the data include the names of the principal investigator responsible for the data collection at each institution. They would be:

1. Hungarian Institute of Cardiology. Budapest: Andras Janosi, M.D.
2. University Hospital, Zurich, Switzerland: William Steinbrunn, M.D.
3. University Hospital, Basel, Switzerland: Matthias Pfisterer, M.D.
4. V.A. Medical Center, Long Beach and Cleveland Clinic Foundation:Robert Detrano, M.D., Ph.D.

## Aims and Objectives:
To be filled after performing Exploratory Data Analysis (EDA).

### Import libraries
Let's begin by importing all the required libraries.

In [ ]:
# import libraries

# to handle data
import pandas as pd
import numpy as np

# to visualize the data
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# to preprocess the data
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.impute import SimpleImputer, KNNImputer
# import iterative imputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# for machine learning task
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
# for classification task
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier, RandomForestRegressor
from xgboost import XGBClassifier
# metrics
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, r2_score, mean_absolute_error, mean_squared_error

# ignore warnings
import warnings
warnings.filterwarnings('ignore')

### Loading DataSet

In [ ]:
# load the locally present datafile
df = pd.read_csv('/kaggle/input/heart-disease-data/heart_disease_uci.csv')

# display the first 5 rows
df.head()

---
## <span style="color:red">**Exploratory Data Analysis (EDA)**</span>

### Exploring each column

In [ ]:
# exploring the dataset
df.info()

In [ ]:
# data shape
df.shape

#### Let's explore `age` column:

In [ ]:
# summarize age column
df['age'].describe()

In [ ]:
# age column min max
df['age'].min(), df['age'].max()

In [ ]:
# draw a histogram for age distribution
plt.figure(figsize=(10, 6))
sns.histplot(df['age'], kde=True, color='red')

In [ ]:
# plot mean median and mode of age column
plt.figure(figsize=(10, 6))
sns.kdeplot(df['age'], color='red', shade=True)
plt.axvline(df['age'].mean(), color='red', label='Mean')
plt.axvline(df['age'].median(), color='green', label='Median')
plt.axvline(df['age'].mode()[0], color='blue', label='Mode')
plt.legend()
plt.show()

In [ ]:
# print mean, median and mode values in f string
print(f"Mean: {df['age'].mean()}")
print(f"Median: {df['age'].median()}")
print(f"Mode: {df['age'].mode()[0]}")

Let's explore the gender based distribution of age column

In [ ]:
# plot histogram of age column using plotly and color on sex basis
fig = px.histogram(df, x='age', color='sex')
fig.show()

In [ ]:
# value counts of sex column
df['sex'].value_counts()

In [ ]:
# calculate percentages of male and female value counts
male_count = 726
female_count = 194
total_count = male_count + female_count
male_percentage = (male_count / total_count) * 100
female_percentage = (female_count / total_count) * 100
# print percentages with f string
print(f"Male percentage having heart disease in data: {male_percentage:.2f}%")
print(f"Female percentage having heart disease in data: {female_percentage:.2f}%")

# how much times male are of females
times = (male_count - female_count) / female_count
print(f'Males are {times:.2f} times more than females.')

In [ ]:
# find the value of age column grouping by sex column
df.groupby('sex')['age'].value_counts()

#### <span style="color:red">**Observations from `age` column:**</span>
1. The minimum age reported with heart disease is `28 years`.
2. The maximum age reported with heart disease is `77 years`.
3. From histogram, most cases are reported in 50-60 years age range.
4. More precisely, most people get heart disease at age of 53-54 years.
5. On gender basis, most of the male and female both get heart disease at age of 54-55 years.
6. Male percentage having heart disease in data: 78.91%.
7. Female percentage having heart disease in data: 21.09%.
8. Males are 2.74 times more than females.

#### Exploring `dataset` column:

In [ ]:
# Let's deal with dataset column

# have a look at unique values
df['dataset'].unique()

In [ ]:
# dataset column value counts
df['dataset'].value_counts()

In [ ]:
# count plot of dataset column with plotly
fig = px.bar(df, x='dataset', color='sex')
fig.show()

In [ ]:
# value count of dataset column with groupby sex
df.groupby('sex')['dataset'].value_counts()

In [ ]:
# plot in plotly age column and color on base of dataset column
fig = px.histogram(df, x='age', color='dataset')
fig.show()

In [ ]:
# print mean, median and mode of age grouped by dataset column
print("Mean:\n", df.groupby('dataset')['age'].mean())
print('============================')
print("Median:\n", df.groupby('dataset')['age'].median())
print('============================')
print("Mode:\n", df.groupby('dataset')['age'].agg(lambda x: x.mode().values[0]))
print('============================')

#### <span style="color:red">**Observations from `dataset` column:**</span>
1. DataSet is from 4 different places.
2. We have highest number of people from `Cleveland` (304) and lowest from `Switzerland` (123).
3. The highest number of females in this data are from `Cleveland` (97) and lowest from `VA Long Beach` (6).
4. The highest number of males in this data are from `Hungary` (202) and lowest from `Switzerland` (113).
5. Mean, median and mode of `dataset` column grouped by age are as:
   - Mean:
     - Cleveland = 54.351974
     - Hungary = 47.894198
     - Switzerland = 55.317073
     - VA Long Beach = 59.350000
   - Median:
     - Cleveland = 55.5
     - Hungary = 49.0
     - Switzerland = 56.0
     - VA Long Beach = 60.0
   - Mode:
     - Cleveland        58
     - Hungary          54
     - Switzerland      61
     - VA Long Beach    62

#### Exploring `cp` (Chest Pain) column

In [ ]:
# value count of cp column
df['cp'].value_counts()

In [ ]:
# plot of cp column grouped by age column using plotly
fig = px.histogram(df, x='age', color='cp')
fig.show()

In [ ]:
# count plot of cp column grouped by sex
sns.countplot(df, x='cp', hue='sex')

In [ ]:
# value count of cp grouped by sex
df.groupby('sex')['cp'].value_counts()

In [ ]:
# count plot of cp column grouped by dataset column
sns.countplot(df, x='cp', hue='dataset')

In [ ]:
# value count of cp grouped by dataset column
df.groupby('dataset')['cp'].value_counts()

#### <span style="color:red">**Observations from `cp` column:**</span>
1. Highest number of people have chest pain type `asymptomatic` (946).
2. Lowest number of people have chest pain type `typical angina` (46).
3. Chest pain type `asymptomatic` is highest in both males (426) and females (70).
4. Same trend is being followed in `dataset` column.
5. `asymtomatic` type pain being most common is having following distribution in `dataset` column:
   - Cleveland = 144
   - VA Long Beach = 131
   - Hungary = 123
   - Switzerland = 98
1. Highest number of people have chest pain type `asymptomatic` (946).
2. Lowest number of people have chest pain type `typical angina` (46).
3. Chest pain type `asymptomatic` is highest in both males (426) and females (70).
4. Same trend is being followed in `dataset` column.
5. `asymtomatic` type pain being most common is having following distribution in `dataset` column:
   - Cleveland = 144
   - VA Long Beach = 131
   - Hungary = 123
   - Switzerland = 98

#### Let's explore `trestbps` (resting blood pressure) column:
The normal resting blood pressure is 120/80 mm Hg.

In [ ]:
# description of trestbps column
df['trestbps'].describe()

In [ ]:
# histplot of trestbps column
plt.figure(figsize=(10, 6))
sns.histplot(df['trestbps'], kde=True, color='red')

In [ ]:
# plot of trestbps grouped by dataset
fig = px.histogram(df, x='trestbps', color='dataset')
fig.show()

In [ ]:
# plot of trestbps grouped by sex
fig = px.histogram(df, x='trestbps', color='sex')
fig.show()

In [ ]:
# checking for missing values in trestbps
df['trestbps'].isnull().sum()

#### <span style="color:red">**Observations from `trestpbs` column:**</span>
1. The minimum value of resting blood pressure is noted `0 mm Hg` which is not possible so it is considered outlier.
2. The maximum value of resting blood pressure is noted `200 mm Hg`.
3. There are 59 missing values noted in this column which will be imputed in later section.
4. Most values of trestbps are concentrated in the interval 120-140 mm Hg.
5. There is no signigicant difference in the distribution of trestbps values if grouped by `sex` or `dataset`.

#### Let's explore `chol` (serum cholesterol in mg/dl) column:
A normal total cholesterol level for adults is less than 200 milligrams per deciliter (mg/dL). Levels between 200 and 239 mg/dL are considered borderline high, and levels of 240 mg/dL or higher are considered high.

In [ ]:
# histplot of chol column
plt.figure(figsize=(10, 6))
sns.histplot(df['chol'], kde=True, color='red')

In [ ]:
# to check how many '0' values are present
df['chol'].value_counts()

In [ ]:
# groupby sex column
df.groupby('chol')['sex'].value_counts()

In [ ]:
# groupby sex column
df.groupby('chol')['sex'].value_counts()

In [ ]:
# plot of chol groupby dataset using ploly
fig = px.histogram(df, x='chol', color='dataset')
fig.show()

In [ ]:
# plot of chol groupby sex using ploly
fig = px.histogram(df, x='chol', color='sex')
fig.show()

In [ ]:
# missing values in chol
df['chol'].isnull().sum()

#### <span style="color:red">**Observations from `chol` column:**</span>
1. The data is having 172 entries of 0 mg/dL cholestrol level values which is far from normal range so, it will be dealt later.
2. The 172 entries of 0 mg/dL cholestrol level values comprises of 161 males and 11 females.
3. **`An important thing noticed`** that there are total 123 entries from Switzerland and all have cholestrol level value 0 mg/dL which is an error on behalf of data collection.
4. The rest of 49 entries are from VA Long Beach.
5. `chol` also contain 30 missing values.

#### Let's explore `fbs` (if fasting blood sugar > 120 mg/dl) column:
A fasting blood sugar level of 70â€“100 mg/dL is considered normal, according to the World Health Organization (WHO). Here > 120 md/dL is considered diabetic and stated `True` and lower non-diabetic stated `False`.

In [ ]:
# value counts of fbs
df['fbs'].value_counts()

In [ ]:
# missing values in fbs
df['fbs'].isnull().sum()

In [ ]:
# histplot of fbs with color sex using plotly
fig = px.histogram(df, x='fbs', color='sex')
fig.show()

In [ ]:
# histplot of fbs with color dataset using plotly
fig = px.histogram(df, x='fbs', color='dataset')
fig.show()

#### <span style="color:red">**Observations from `fbs` column:**</span>
1. `fbs` contains 90 missing values.
2. Out of all patients reported 692 are non-diabetic and 138 are diabetic.
3. The distribution of data is pretty much same if grouped by `sex` or `dataset` as most of people are non-diabetic and some are diabetic. So there is no specific or notable pattern here.

#### Let's explore `restecg` (resting electrocardiographic results) column:
**Values:** [normal, stt abnormality, lv hypertrophy]

In [ ]:
# value counts of restecg
df['restecg'].value_counts()

In [ ]:
# countplot of restecg
sns.countplot(df, x='restecg')

In [ ]:
# missing values in restecg
df['restecg'].isnull().sum()

In [ ]:
# plot of dataset grouped by restecg using plotly
fig = px.histogram(df, x='dataset', color='restecg')
fig.show()

#### <span style="color:red">**Observations from `restecg` column:**</span>
1. There are 551 people with normal value of restecg.
2. There are 188 people with lv hypertrophy value of restecg.
3. There are 179 people with st-t abnormality value of restecg.
4. There are 2 missing values.
5. Most of the people with:
   - Normal value are from Hungary.
   - st-t abnormality are from VA Long Beach.
   - lv hypertrophy are from Cleveland.

#### Let's explore `thalch` (maximum heart rate achieved) column:
A normal resting heart rate for an adult is between 60 and 100 beats per minute (bpm).

In [ ]:
# summary of thalch
df['thalch'].describe()

In [ ]:
# missing values in thalch
print(f"There are {df['thalch'].isnull().sum()} missing values.")

In [ ]:
# plotting thalch
plt.figure(figsize=(10, 6))
sns.histplot(df['thalch'], kde=True, color='red')

In [ ]:
# plotting thalch with color sex using plotly
fig = px.histogram(df, x='thalch', color='sex')
fig.show()

#### <span style="color:red">**Observations from `thalch` column:**</span>
1. The maximum value reported in `thalch` is 202.
2. The minimum value reported is 60.
3. There are 55 missing values.
4. The mean of max. heart rate achieved is 137.545665.

#### Let's explore `exang` (exercise-induced angina) column:
Exercise-induced angina is chest pain that occurs when the heart works harder during exercise or other physical activity.\
This is a boolean variable.

In [ ]:
# summary of exang
df['exang'].describe()

In [ ]:
# value counts of exang
df['exang'].value_counts()

In [ ]:
# missing values in exang
df['exang'].isnull().sum()

In [ ]:
# plot of exang with color sex using plotly
fig = px.histogram(df, x='dataset', color= 'exang')
fig.show()

#### <span style="color:red">**Observations from `thalch` column:**</span>
1. There are 337 people that have problem with exercise induced angina.
2. Whereas other 528 donot have any such issues.
3. There are 55 missing values.
4. Out of those who doesnot have any issue are mostly from Cleveland and Hungary. Whereas those with problem are least from Switzerland.

#### Let's explore `oldpeak` (ST depression induced by exercise relative to rest) column:
ST depression refers to a finding on an electrocardiogram(ECG), wherein the trace in the ST segment is abnormally low below the baseline.\
ST segment depression (ST depression) is considered normal if it's less than 0.5 millimeters (mm) in all leads.

In [ ]:
# oldpeak summary
df['oldpeak'].describe()

In [ ]:
# missing values in oldpeak
print(f"There are {df['oldpeak'].isnull().sum()} missing values.")

In [ ]:
# plot of oldpeak with color sex using plotly
fig = px.histogram(df, x='oldpeak', color='dataset')
fig.show()

#### <span style="color:red">**Observations from `oldpeak` column:**</span>
1. The minimum ST depression value is -2.6 mm and maximum value is 6.2 mm.
2. The average value reported is 0.878788 mm.
3. There are 62 missing values.
4. Most repeated value of ST depression is 0.

#### Let's explore `slope` (the slope of the peak exercise ST segment) column:
**Values**: [flat, upsloping, downsloping]

In [ ]:
# value counts of slope
df['slope'].value_counts()

In [ ]:
# missing values in slope
print(f"There are {df['slope'].isnull().sum()} missing values.")

In [ ]:
# plot of slope with color sex using plotly
fig = px.histogram(df, x='slope', color='sex')
fig.show()

In [ ]:
# plot of slope with color dataset using plotly
fig = px.histogram(df, x='slope', color='dataset')
fig.show()

#### <span style="color:red">**Observations from `slope` column:**</span>
1. The distribution of people in the `slope` column is as:
   - flat = 345
   - upsloping = 203
   - downsloping = 63
2. There are 309 missing values.
3. The upsloping is considerabely more in females as compared to males.
4. Whereas downsloping is more in males as compared to females.
5. Similarly there is trend in `dataset` column regarding slope:
   - Upsloping is dominant in Cleveland.
   - Downsloping is dominant in VA Long Beach.

#### Let's explore `ca` (number of major vessels (0-3) colored by fluoroscopy) column:

In [ ]:
# value counts of ca
df['ca'].value_counts()

In [ ]:
# missing values in ca
print(f"There are {df['ca'].isnull().sum()} missing values.")

In [ ]:
# value count of ca grouped by dataset
df.groupby('ca')['dataset'].value_counts()

In [ ]:
# plot of ca with color sex using plotly
fig = px.histogram(df, x='dataset', color='ca')
fig.show()

#### <span style="color:red">**Observations from `ca` column:**</span>
1. There are 611 missing values.
2. Most number of people (181) have 0 number of vessels controlled.
3. On `dataset` basis `ca` have following distribution:
   - 0.0
     - Cleveland = 176
     - Hungary = 3
     - VA Long Beach = 2
   - 1.0
     - Cleveland = 65
     - Switzerland = 2
   - 2.0
     - Cleveland = 38
     - Switzerland = 3
   - 3.0
     - Cleveland = 20

#### Let's explore `thal` (blood disorder called thalassemia) column:
**Values:** [normal, fixed defect, reversible defect]

In [ ]:
# value counts of thal
df['thal'].value_counts()

In [ ]:
# missing values in thal
print(f"There are {df['thal'].isnull().sum()} missing values.")

In [ ]:
# plot of thal grouped by dataset using plotly
fig = px.histogram(df, x='dataset', color='thal')
fig.show()

In [ ]:
# plot of thal grouped by sex using plotly
fig = px.histogram(df, x='thal', color='sex', barmode='group', title='Thalassemia by Sex')
fig.show()

#### <span style="color:red">**Observations from `thal` column:**</span>
1. There are 486 missing values.
2. The fixed defect has different distribution than other value counts as it has significant number in countries other than Cleveland too. Whereas other value count does not have any significant number in other countries.
3. On gender basis, females have far less reversible defect as compared to that of males.

#### Let's explore `num` (the predicted attribute) column:

In [ ]:
# value count of num
df['num'].value_counts()

In [ ]:
# missing values in num
print(f"There are {df['num'].isnull().sum()} missing values.")

In [ ]:
# value count of num grouped by dataset
df.groupby('num')['dataset'].value_counts()

In [ ]:
# plot of num grouped by sex using plotly
fig = px.histogram(df, x='dataset', color='num')
fig.show()

#### <span style="color:red">**Observations from `num` column:**</span>
1. This is the prediction whether certain individual have heart disease or not.
2. **Values:** 0 = No heart disease, 1,2,3,4 = Different stages of heart disease

---

## <span style="color: red; font-weight: bold;">Dealing with missing values</span>

A fuction will be defined to get the job done!

In [ ]:
df.isnull().sum()[df.isnull().sum() > 0].sort_values(ascending=False)
missing_data_cols = df.isnull().sum()[df.isnull().sum() > 0].index.tolist()
missing_data_cols

In [ ]:
categorical_cols = ['thal', 'ca', 'slope', 'exang', 'restecg','fbs', 'cp', 'sex', 'num']
bool_cols = ['fbs', 'exang']
numeric_cols = ['oldpeak', 'thalch', 'chol', 'trestbps', 'age']

In [ ]:
# define the function to impute the missing values in thal column

def impute_categorical_missing_data(passed_col):
    
    df_null = df[df[passed_col].isnull()]
    df_not_null = df[df[passed_col].notnull()]

    X = df_not_null.drop(passed_col, axis=1)
    y = df_not_null[passed_col]
    
    other_missing_cols = [col for col in missing_data_cols if col != passed_col]
    
    label_encoder = LabelEncoder()

    for col in X.columns:
        if X[col].dtype == 'object' or X[col].dtype == 'category':
            X[col] = label_encoder.fit_transform(X[col])

    if passed_col in bool_cols:
        y = label_encoder.fit_transform(y)
        
    iterative_imputer = IterativeImputer(estimator=RandomForestRegressor(random_state=42), add_indicator=True)

    for col in other_missing_cols:
        if X[col].isnull().sum() > 0:
            col_with_missing_values = X[col].values.reshape(-1, 1)
            imputed_values = iterative_imputer.fit_transform(col_with_missing_values)
            X[col] = imputed_values[:, 0]
        else:
            pass
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    rf_classifier = RandomForestClassifier()

    rf_classifier.fit(X_train, y_train)

    y_pred = rf_classifier.predict(X_test)

    acc_score = accuracy_score(y_test, y_pred)

    print("The feature '"+ passed_col+ "' has been imputed with", round((acc_score * 100), 2), "accuracy\n")

    X = df_null.drop(passed_col, axis=1)

    for col in X.columns:
        if X[col].dtype == 'object' or X[col].dtype == 'category':
            X[col] = label_encoder.fit_transform(X[col])

    for col in other_missing_cols:
        if X[col].isnull().sum() > 0:
            col_with_missing_values = X[col].values.reshape(-1, 1)
            imputed_values = iterative_imputer.fit_transform(col_with_missing_values)
            X[col] = imputed_values[:, 0]
        else:
            pass
                
    if len(df_null) > 0: 
        df_null[passed_col] = rf_classifier.predict(X)
        if passed_col in bool_cols:
            df_null[passed_col] = df_null[passed_col].map({0: False, 1: True})
        else:
            pass
    else:
        pass

    df_combined = pd.concat([df_not_null, df_null])
    
    return df_combined[passed_col]

def impute_continuous_missing_data(passed_col):
    
    df_null = df[df[passed_col].isnull()]
    df_not_null = df[df[passed_col].notnull()]

    X = df_not_null.drop(passed_col, axis=1)
    y = df_not_null[passed_col]
    
    other_missing_cols = [col for col in missing_data_cols if col != passed_col]
    
    label_encoder = LabelEncoder()

    for col in X.columns:
        if X[col].dtype == 'object' or X[col].dtype == 'category':
            X[col] = label_encoder.fit_transform(X[col])
    
    iterative_imputer = IterativeImputer(estimator=RandomForestRegressor(random_state=42), add_indicator=True)

    for col in other_missing_cols:
        if X[col].isnull().sum() > 0:
            col_with_missing_values = X[col].values.reshape(-1, 1)
            imputed_values = iterative_imputer.fit_transform(col_with_missing_values)
            X[col] = imputed_values[:, 0]
        else:
            pass
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    rf_regressor = RandomForestRegressor()

    rf_regressor.fit(X_train, y_train)

    y_pred = rf_regressor.predict(X_test)

    print("MAE =", mean_absolute_error(y_test, y_pred), "\n")
    print("RMSE =", mean_squared_error(y_test, y_pred, squared=False), "\n")
    print("R2 =", r2_score(y_test, y_pred), "\n")

    X = df_null.drop(passed_col, axis=1)

    for col in X.columns:
        if X[col].dtype == 'object' or X[col].dtype == 'category':
            X[col] = label_encoder.fit_transform(X[col])

    for col in other_missing_cols:
        if X[col].isnull().sum() > 0:
            col_with_missing_values = X[col].values.reshape(-1, 1)
            imputed_values = iterative_imputer.fit_transform(col_with_missing_values)
            X[col] = imputed_values[:, 0]
        else:
            pass
                
    if len(df_null) > 0: 
        df_null[passed_col] = rf_regressor.predict(X)
    else:
        pass

    df_combined = pd.concat([df_not_null, df_null])
    
    return df_combined[passed_col]

In [ ]:
df.isnull().sum()[df.isnull().sum() > 0].sort_values(ascending=False)

In [ ]:
# impute missing values using our functions
for col in missing_data_cols:
    print("Missing Values", col, ":", str(round((df[col].isnull().sum() / len(df)) * 100, 2))+"%")
    if col in categorical_cols:
        df[col] = impute_categorical_missing_data(col)
    elif col in numeric_cols:
        df[col] = impute_continuous_missing_data(col)
    else:
        pass

In [ ]:
df.isnull().sum()

### Missing Values Imputation Key Steps:
- We `separated columns` containing missing values in an object.
- Out of all the columns, `categorical, bool and numeric type` columns were separated.
- We then `defined two functions`, one for `numeric` data type imputation and other for `non-numeric` datatype imputation.
- These functions used the strategy of `Random Forest Classifier` and `Random Forest Regressor` for imputing non-numeric and numeric columns respectively.
- In the end, used a `for loop to impute all` the mmissing values by passing columns into functions.

---
## <span style="color: red; font-weight: bold;">Dealing with Outliers</span>

In [ ]:
# boxplot for all numeric columns with different colors and using for loop and subplot
fig = go.Figure()

for i, col in enumerate(numeric_cols):
    fig.add_trace(go.Box(x=df[col], name=col))

fig.update_layout(title="Boxplot for Numeric Columns",
                  xaxis_title="Columns",
                  yaxis_title="Values")

fig.show()

In [ ]:
# print the row where trestbps is 0
df[df['trestbps'] == 0]

# drop the row where trestbps is 0
df = df[df['trestbps'] != 0]

- `0` values in `chol` column will be treated specially later on.
- Here is just a glimpse of those values.

In [ ]:
# print the row where chol is 0
df[df['chol'] == 0]

In [ ]:
# replacing the 0 in chol column with nan
df['chol'] = df['chol'].replace(0, np.nan)
# display rows where chol has missing value

df[df['chol'].isnull()]

In [ ]:
df['chol'].isnull().sum()

In [ ]:
# imputing these using function
df['chol'] = impute_continuous_missing_data('chol')

# check of they are imputed
df['chol'].isnull().sum()

---
## <span style="color: red; font-weight: bold;">Machine Learning</span>

The target column is `num` which is the predicted attribute. This column will be use to predict heart disease.
The unique values in this column are: [0, 1 ,2 ,3 ,4] which states there are 5 unique types of heart disease.
* `0 = No Heart Disease`
* `1 = Heart Disease Type 1`
* `2 = Heart Disease Type 2`
* `3 = Heart Disease Type 3`
* `4 = Heart Disease Type 4`

In [ ]:
# split the data into X and y
X = df.drop('num', axis=1)
y = df['num']

# encode all the categorical column using separate encoder for each and save for inverse transform
label_encoders = {}
for col in X.columns:
    if X[col].dtype == 'object' or X[col].dtype == 'category':
        label_encoders[col] = LabelEncoder()
        X[col] = label_encoders[col].fit_transform(X[col])
    else:
        pass


# train test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

Enlisting all the models to be used. These are models that work for multi-class classification.
1. Logistic Regression
2. K-Nearest Neighbour (KNN)
3. Decision Tree
4. Naive Bayes (NB)
5. Support Vector Machines (SVM)
6. Random Forest
7. XGBoost
8. AdaBoost
9. Gradient Boosting
10. lightGBM

In [ ]:
# import all models stated
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier, plot_tree 
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.naive_bayes import GaussianNB

# import pipeline
from sklearn.pipeline import Pipeline

In [ ]:
# create a dictionary of models
models = {
    'Logistic Regression': LogisticRegression(random_state=42),
    'KNN': KNeighborsClassifier(),
    'SVC': SVC(random_state=42),
    'Decision Tree': DecisionTreeClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42),
    'AdaBoost': AdaBoostClassifier(random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(random_state=42),
    'XGBoost': XGBClassifier(random_state=42),
    'LGBM': LGBMClassifier(random_state=42),
    'Naive Bayes': GaussianNB()
}

best_model = None
best_accuracy = 0.0

# Iterate over the models and evaluate their performance
for name, model in models.items():
    # Create a pipeline for each model
    pipeline = Pipeline([('model', model)])
    
    # Perform cross-validation
    scores = cross_val_score(pipeline, X_train, y_train, cv=5)
    
    # Calculate mean accuracy
    mean_accuracy = scores.mean()
    
    # Fit the pipeline on the training data
    pipeline.fit(X_train, y_train)
    
    # Make predictions on the test data
    y_pred = pipeline.predict(X_test)
    
    # Calculate accuracy score
    accuracy = accuracy_score(y_test, y_pred)
    
    # Print the performance metrics
    print("Model:", name)
    print("Cross-validation Accuracy:", mean_accuracy)
    print("Test Accuracy:", accuracy)
    print()
    
    # Check if the current model has the best accuracy
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_model = pipeline

# Retrieve the best model
print("Best Model:", best_model)

# save best model using pickle
import pickle
with open('best_model_heart_disease.pkl', 'wb') as file:
    pickle.dump(best_model, file)

In [ ]:
# load the saved model
with open('best_model_heart_disease.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

# make predictions using loaded model
y_pred = loaded_model.predict(X_test)

# calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# confusion matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion Matrix\n', cm)

# classification report
cr = classification_report(y_test, y_pred)
print('Classification Report\n', cr)

In [ ]:
# heatplot of confusion matrix
plt.figure(figsize=(10, 6))
sns.heatmap(cm, annot=True, cmap='viridis', fmt='d', cbar=True)

In [ ]:
df.sample(5)

---
## <span style="color: red; font-weight: bold;">Prediction</span>

In [ ]:
# sample prediction
sample_data = {'id': 920,
               'age': 51,
               'sex': 1,
               'dataset': 3,
               'cp': 2,
               'trestbps': 130,
               'chol': 350,
               'fbs': 0,
               'restecg': 0,
               'thalch': 142,
               'exang': 1,
               'oldpeak': 3.5,
               'slope': 3,
               'ca': 2,
               'thal': 2}

# convert to dataframe
sample_df = pd.DataFrame([sample_data])

# make prediction
prediction = loaded_model.predict(sample_df)
prediction